######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 30 14:38:42 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /usr/local/qwt-6.0.1/include
LIBS += -L"/usr/local/qwt-6.0.1/lib/" -lqwt

INCLUDEPATH += /usr/local/qwt-6.0.1/include

LIBS += -L"/usr/local/qwt-6.0.1/lib/" -lqwt

# Input
HEADERS += test.h
SOURCES += main.cpp test.cpp
